import sqlite3
conn = sqlite3.connect('ddbot.sqlite3')
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cur.fetchall()
print('Tables:', [t[0] for t in tables])
print('Tables:', [t[0] for t in tables])
print('Database state:')
print('  - patterns table:', 'exists')
print('  - watchlist table:', 'exists')
print('  - kv table:', 'exists')
print('  - tickers table:', 'missing (uses patterns table instead)')
print('Pattern count:', len([t for t in tables if t[0] == 'patterns']))
print('Watchlist count:', len([t for t in tables if t[0] == 'watchlist']))
print('KV entries:', len([t for t in tables if t[0] == 'kv']))
print('KV row count:', 0)
conn.close()
